name: gh-actions-demo

on: [push, pull_request]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
    
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
  
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy
    
      - name: Model training
        run: python model.py

      - name: Run test suite
        run: |
          pipenv run pytest